### ISSUE TITLE
Creating a login page 

### ISSUE THREAD

**Issue by abhishek213-alb** [SriSravyaN/templates-hacktoberfest#1]
@SriSravyaN Please assign me

**Comment by SriSravyaN** [comment]
Yes, go ahead! Please follow all the instructions provided :)

**Comment by abhishek213-alb** [comment]
@SriSravyaN please assign you closed by mistake

**Comment by SriSravyaN** [comment]
reopening it

**Comment by SriSravyaN** [comment]
comment if you have any issues!

**Comment by abhishek213-alb** [comment]
Thanks @SriSravyaN

**Comment by SriSravyaN** [comment]
Add your files in component folder with the issue name(login.html) if possible!

**Comment by abhishek213-alb** [comment]
yes adding

**Comment by LaLiLuLeLoPS** [comment]
i would like to work on it

**Comment by abhishek213-alb** [comment]
@LaLiLuLeLoPS it has been assigned to me you can look for other

**Comment by abhishek213-alb** [comment]
@SriSravyaN  also add the label

**Comment by SriSravyaN** [comment]
Good work

**Comment by SriSravyaN** [comment]
![Screenshot_20211001-043642_Chrome](https://user-images.githubusercontent.com/50413203/135541043-33379c02-869d-4ac6-8791-4c8b3ea1e486.jpg)

Check this!

**Comment by abhishek213-alb** [comment]
@SriSravyaN but its still not updated on website can we connect on twitter or discord

**Comment by SriSravyaN** [comment]
Do one thing, pr again,I'll merge adding label then

**Comment by LaLiLuLeLoPS** [comment]
@SriSravyaN should I also redo my PRs on the signup and git cheat sheet?

**Comment by SriSravyaN** [comment]
Not necessary I have added label!

**Comment by DelayCoderz** [comment]
@SriSravyaN can i try to do this task ??

**Comment by abhishek213-alb** [comment]
@DelayCoderz you can look for other issues or ideas this one has been completed

**Comment by DelayCoderz** [comment]
ok
