### ISSUE TITLE
create portfolio template

### ISSUE THREAD

**Issue by SriSravyaN** [SriSravyaN/templates-hacktoberfest#13]
Using this template, people can reuse it to make their own portfolio!

If yes, Do comment,I will assign it :)

**Comment by Pensuveze** [comment]
yes I will be happy to do this.I can make the portfolio using html codes

**Comment by SriSravyaN** [comment]
Assigning!

**Comment by belikeakash** [comment]
I want to do this task please assign me.

**Comment by Pensuveze** [comment]
@SriSravyaN  Please close this issue.

**Comment by Pensuveze** [comment]
> I want to do this task please assign me.

Already submitted this issue Brother.Find another one please.

**Comment by SriSravyaN** [comment]
> I want to do this task please assign me.

Create a different one from existing one.

**Comment by SriSravyaN** [comment]
Only then it will be merged

**Comment by Pensuveze** [comment]
Mam if possible close this issue so that no other person can do this task..
Thanks

**Comment by SriSravyaN** [comment]
Yes!
