### ISSUE TITLE
create cheatsheet for "How to a make pull request"

### ISSUE THREAD

**Issue by SriSravyaN** [SriSravyaN/templates-hacktoberfest#16]
It can be a webpage(html/js files) or .md files!

Comment,so that i can assign this!

**Comment by sarthakdelori** [comment]
Hey!, Can I make a "PR through GitHub Desktop" Cheatsheet?

If yes, assign this to me.

**Comment by Anubha13kumari** [comment]
Hi @SriSravyaN ,I can make a cheatsheet for git CLI.

**Comment by SriSravyaN** [comment]
> Hey!, Can I make a "PR through GitHub Desktop" Cheatsheet?
> 
> If yes, assign this to me.

Yes

**Comment by SriSravyaN** [comment]
> Hi @SriSravyaN ,I can make a cheatsheet for git CLI.

Okay!

**Comment by SriSravyaN** [comment]
Add your files in template folder
