### ISSUE TITLE
Create Calculator!

### ISSUE THREAD

**Issue by SriSravyaN** [SriSravyaN/templates-hacktoberfest#18]

**Comment by DelayCoderz** [comment]
can i try to solve this task ??

**Comment by Subrata-Rajak** [comment]
@SriSravyaN  mam can i make an android app to solve this issue??

**Comment by SriSravyaN** [comment]
> @SriSravyaN mam can i make an android app to solve this issue??

Yes

**Comment by SriSravyaN** [comment]
> can i try to solve this task ??

Yes

**Comment by Subrata-Rajak** [comment]
@SriSravyaN mam, I created a pr to add the app file. Please review it and merge if you found it useful. #33 Thank You
