### ISSUE TITLE
Color picker using js

### ISSUE THREAD

**Issue by SriSravyaN** [SriSravyaN/templates-hacktoberfest#19]

**Comment by NotFarFromBlonded** [comment]
Can you assign me this issue?

**Comment by Atharv777** [comment]
I want to work on this I have already read the `contibuting.md` please tell me should I add the file in components or templates folder

**Comment by SriSravyaN** [comment]
Add in component folder

**Comment by Atharv777** [comment]
I am sorry I do not have time to do this but I will be doing #20

**Comment by SriSravyaN** [comment]
> I am sorry I do not have time to do this but I will be doing #20

No problem!

**Comment by BajraYeJoon** [comment]
@SriSravyaN  Can you assign me this ? Also PLease do assign the issue that I have created issue titled as "Animated Login ui" 😃

**Comment by Jibendu007** [comment]
@SriSravyaN can i be assigned to this?
