### ISSUE TITLE
To Create SignUp form

### ISSUE THREAD

**Issue by SriSravyaN** [SriSravyaN/templates-hacktoberfest#2]
Create a signup form in any language you are comfortable with! 
If yes,I can assign this issue,just comment here :)

**Comment by ORKO06** [comment]
I would like to work on it

**Comment by SriSravyaN** [comment]
Great! Pls,go ahead :)

**Comment by LaLiLuLeLoPS** [comment]
I would like to work on it

**Comment by SriSravyaN** [comment]
Yes!!Sure
Be creative,so that pr gets merged !

**Comment by SriSravyaN** [comment]
Add your files only in component folder!
