### ISSUE TITLE
Detailed Git CheatSheet

### ISSUE THREAD

**Issue by SriSravyaN** [SriSravyaN/templates-hacktoberfest#3]
Git commands used on daily basis and important commands 
Add commands along with brief description how they works!
To make more creative,you make it a webpage using HTML!

**Comment by SriSravyaN** [comment]
If yes, do comment!

**Comment by gokhalevedant06** [comment]
Hi, I would like to do this

**Comment by SriSravyaN** [comment]
Assigning!

**Comment by SriSravyaN** [comment]
Suggestion : table format looks neat!

**Comment by SriSravyaN** [comment]
Add your files in template folder!

**Comment by LaLiLuLeLoPS** [comment]
i would like to do this

**Comment by SriSravyaN** [comment]
Assigned!

**Comment by Subrata-Rajak** [comment]
@SriSravyaN mam, I created a pr for the git sheet. I added a command in the sheet. please check that #21
